name: Cart CI pipeline for dev branch
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '!main'
run-name: ${{ github.sha }} | ${{ github.event.head_commit.message }}
jobs:
  deploy:
    uses: dsaniset23/roboshop-actions/.github/workflows/ci-dev-branch.yml@main
    with:
      componentName: cart